### ISSUE TITLE
Compile error with version 0.49.0

### ISSUE THREAD

**Issue by kamcknig** [state-adapt/state-adapt#24]
Getting a compile error with the newest version 0.49.0 for both state-adapt/core and state-adapt/angular.

Using version 14.2.0 of angular

```
Error: node_modules/@state-adapt/core/lib/adapters/build-adapter.function.d.ts:20:74 - error TS2536: Type 'P_1' cannot be used to index type 'R & S & { state: (state: State) => State; } & BasicAdapterMethods<State>'. 20 } & BasicAdapterMethods<State> extends infer T_1 ? { [P_1 in keyof T_1]: (R & S & { ~~~~~~~~~~ 21 state: (state: State) => State; ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 22 } & BasicAdapterMethods<State>)[P_1]; } : never>["selectors"], 19>;
```

**Comment by kamcknig** [comment]
I also get it with version of 14.0.3 of angular which is the last version i was using that I know worked with version 0.48.0 of state-adapt

**Comment by mfp22** [comment]
0.48 doesn't have buildSelectors, but I know it was compiling for me when I released 0.49. What version of TS are you using?

**Comment by kyle-mcknight** [comment]
4.7.2, which is the same version that worked with 0.48.0 as well.

**Comment by mfp22** [comment]
Are you actually using buildAdapter?

Also, do you have a link to your repo or is it just local changes? When I get to my computer I can try it on StackBlitz and see if I can reproduce it. Actually I'm not sure I'll be able to, because I have one on StackBlitz already with 0.49 and Angular 14 and it's working https://stackblitz.com/edit/angular-ivy-cwnz5p?file=src%2Fapp%2Fapp.module.ts

**Comment by kyle-mcknight** [comment]
There's no reference to "buildAdapter" in my code that I can see. So not unless it's being used by something else. 

it's on master and develop https://github.com/kamcknig/gloomhaven-helper

**Comment by kyle-mcknight** [comment]
just update to 0.49.0 , install with --force because of angular 14.2.0.

**Comment by mfp22** [comment]
I forked my stackblitz and moved it to 14.2 and it still compiles. I'll have to pull down your repo

**Comment by kyle-mcknight** [comment]
Must be something I'm using. I tried on a computer that didn't have it previously and same thing. so wasn't a weird npm issue i don't think

**Comment by mfp22** [comment]
What version of node are you using?

**Comment by mfp22** [comment]
I pulled your repo and it's working for node 14.17.6, 16.10 and 18.8.0. I did have to use `npm install --force` for 18.8.0 as you said above, but it looks like it's working anyway. 

Are you on Windows maybe?

**Comment by kyle-mcknight** [comment]
Node version 16.13.1

I am in windows

**Comment by kyle-mcknight** [comment]
I just used nvm to install 16.10.0 of node and it still failed with the  same error. hmm

**Comment by mfp22** [comment]
I'm running it in Windows and just having trouble with NPM install in general. 

I need to release 0.50 soon anyway. I noticed recently that my scripts weren't updating peer dependencies in the dist folder. I need to fix that so it's fine with any Angular minor version (^14.0.3 instead of @14.0.3). I would like to blame an Nx script, but honestly it might have been a problem for a while. 

In version 50, I'm trying out re-exporting all dependencies through `state-adapt/angular`. This is because I need to create a new library for RxJS so I can separate core adapter stuff from RxJS-dependent stuff, so I can support a no-RxJS version in React, SolidJS and Qwik. This would mean people could import `adapt` from either `@state-adapt/rxjs` or `@state-adapt/angular` and that would lead to mistakes. So I thought I should just export everything Angular developers need through `@state-adapt/angular`. 

Anyway, that should be done this week. I will let you know. Then I'll try to reproduce your issue. But I have a feeling there might be a problem with `npm install` somewhere. I know you did it on 2 separate computers and with Angular 14.0, but in my experience with Windows-specific problems, it's from `npm install` 99% of the time, and there might be a side-effect of using `--force`.

**Comment by mfp22** [comment]
Oh and after 0.50, I will create a `createListAdapter` function, and then I should be ready to release StateAdapt 1.0.

**Comment by mfp22** [comment]
My library strategy failed. So I released 0.51. I've separated RxJS from core stuff. It's a little bit of migration, not much. 

But it looks like I've found the same error on MacOS with my new version. But I got another couple of errors. Was the error you posted the only error you got? Here's what I got
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/13700926/189454710-1ff841cd-84ae-4a70-a4d2-bf2b2e0e3a2e.png">

**Comment by kyle-mcknight** [comment]
I only get the one error

![2022-09-09 18_49_54-gloomhaven-helper git – package json](https://user-images.githubusercontent.com/17067600/189455807-c7cc4543-1675-4086-8a70-921cdae8d0b4.png)

**Comment by mfp22** [comment]
I have a solution to the immediate problem. Still trying to figure out why this became an issue in the built TypeScript definitions, because it's not an issue in my source code. But the solution is to change 
```typescript
export type ReactionsFromAdapter<A extends Adapter<any, any, any>> = {
  [K in keyof A]: A[K] extends Reaction<any> ? A[K] : never;
};
```
to 
```typescript
export type ReactionsFromAdapter<A extends Adapter<any, any, any>> = {
  [K in Extract<keyof A, string>]: A[K] extends Reaction<any> ? A[K] : never;
};
```

I found another couple of subtle problems. I'm going to work on getting all of this in the next update. I'll comment again when it's ready for you to try out.

**Comment by mfp22** [comment]
You can also fix this directly in your node_modules if you don't want to wait. In `build-adapter.function.d.ts` on line 16.

**Comment by kyle-mcknight** [comment]
I still have the same error with that.

![2022-09-10 15_05_49-gloomhaven-helper git – E__development_personal_gloomhaven-helper git_node_modul](https://user-images.githubusercontent.com/17067600/189498226-e52adcde-66ec-48ed-a314-81f5e3840239.png)

**Comment by mfp22** [comment]
Ugh. I just discovered that too. It appears this fixes it in my local prod build, but not in your repo. It's the same general issue, just need to find out where to put it in the source code to get the exact right spot. 

If you still want to fix it, you actually need to change line 20 from 

```typescript
} & BasicAdapterMethods<State> extends infer T_1 ? { [P_1 in keyof T_1]: (R & S & {
```
to
```typescript
} & BasicAdapterMethods<State> extends infer T_1 ? { [P_1 in Extract<keyof T_1, string>]: (R & S & {
```

**Comment by mfp22** [comment]
Alright, fixed it for real this time. That's the correct fix locally. The real fix will be in version 0.54.0. Yeah, I have been struggling with builds and versions :)

**Comment by kyle-mcknight** [comment]
With the new version I can't get correct imports for Source or joinSelectors from @state-adapt/core.
![2022-09-10 16_17_16-gloomhaven-helper git – app service ts](https://user-images.githubusercontent.com/17067600/189500454-c046b4b9-b3c4-4f02-8c78-32eff13889b2.png)

**Comment by mfp22** [comment]
Those are now exported from @state-adapt/rxjs

**Comment by kyle-mcknight** [comment]
I can now run it with import from @state-adapt/rxjs and the hack to the build-adapter.function.d.ts

**Comment by mfp22** [comment]
Good! I'll keep this issue open until I get the next release out.

**Comment by mfp22** [comment]
0.54.0 is out.
